Features/task 1
medvedovic/kentico-onboarding-cs pull request #2
Opened 2017-08-29 11:25 UTC by medvedovic

2017-09-05 13:52 UTC, tobiaskamenicky requested changes
Really good job for the first review. You complicated this task by doing two tasks at the same time. 
There are a lot of comments but most of them are really just minor things. 
Most of the comments are applicable to more places, try to look for theses issues elsewhere.

There are few general things I would recommend...
1. You probably created MVC application. Please remove all files and folders that should not be part of the Web API, e.g. AppData, Content. They are really confusing.
2. There should be a service built upon the repository.
3. It is not necessary (I think) to have two API versions alongside...it is enough to have a single API and a single repository/service.
4. Repositories should be located in a separate project.
5. Consider merging all test classes for a single controller into a single class.
6. For my taste, your commits are too granular. I think fewer commit would be easier to read... But it is just my opinion ( since I always forget to commit my work :D)

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/App_Start/RouteConfig.cs
> +            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");
What is this used for?

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/App_Start/WebApiConfig.cs
> +            var container = new UnityContainer();
This should be at least extracted into a new method. It would be better to extract this into another file with `Register` method, that would be called from Global.asax

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/App_Start/WebApiConfig.cs
> +            container.RegisterType<ITodoRepository, TodoRepository>(new HierarchicalLifetimeManager());
Maybe` ContainerControlledLifetimeManager` would be better since it creates a singleton...https://msdn.microsoft.com/en-us/library/ff660872(v=pandp.20).aspx

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Controllers/Todos2Controller.cs
> +    [Route("api/v{version:apiVersion}/Todos/{id:int?}", Name = "TodosV2")]
Url paths are usually lowercase.
Is it necessary to include id in controller route?

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Controllers/Todos2Controller.cs
> +    public class TodosV2Controller : ApiController
File should have the same name as the class

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Controllers/Todos2Controller.cs
> +                .ContinueWith<IHttpActionResult>(res =>
Do not write the controllers like this. In case that you have multiple async calls, it would get really messy. It is also not clear what are you trying to accomplish. Just write simple `var item = _repository.GetAsync(id)`. Then you can check what result should be returned.

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Controllers/Todos2Controller.cs
> +                    .ContinueWith<IHttpActionResult>(res => CreatedAtRoute("TodosV2", new { id = res.Result.Id }, res.Result));
Location creator might be available as a new service with an interface. The main reason is that it should be tested  (in the future).

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Controllers/Todos2Controller.cs
> +                return BadRequest(ex.Message);
You should be consistent with returned objects. The BadRequest is returned with the ModelState earlier. You can use method `ModelState.AddModelError()` to add custom errors.

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Models/Todo.cs
> +        public int Id { get; set; }
The `Guid` type should be used as an identifier. It is easier to generate unique `Guid`.

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Repositories/IAsyncTodoRepository.cs
> +        List<Todo> Todos { get; }
This should not be part of the interface but rather the part of the implementation. You don't need to expose this list when you have methods providing this possibility.

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Repositories/TodoRepository.cs
> +        {
`=> Todos;` ?

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Repositories/TodoRepository.cs
> +                throw new ArgumentNullException("todo");
Rather use `nameof()` method

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Repositories/TodoRepository.cs
> +                todo.Id = nextId++;
Not really thread safe...

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Repositories/TodoRepository.cs
> +            .ContinueWith((prevResult) =>
Use of this was mentioned before...I would recommend finding some further study materials on async and Tasks...

2017-09-05 13:52 UTC, tobiaskamenicky commented on TodoApp/TodoApp.Api/Repositories/TodoRepository.cs
> +            Todos.Remove(todoToRemove);
You can make this shorter if you read documentation for `Remove()` method ;)

2017-09-05 13:52 UTC, sutrkiller commented on TodoApp/TodoApp.Api.Tests/Controllers/DummyControllerTests_Delete.cs
> +            var mockRepository = Substitute.For<ITodoRepository>();
Consider extracting duplicate code to `[SetUp]` method

2017-09-05 13:52 UTC, sutrkiller commented on TodoApp/TodoApp.Api.Tests/Controllers/DummyControllerTests_Delete.cs
> +
Please do not add multiple new lines.

2017-09-05 13:52 UTC, sutrkiller commented on TodoApp/TodoApp.Api.Tests/Controllers/DummyControllerTests_Delete.cs
> +            var response = controller.DeleteTodoAsync(50);
This might not work as you are now awaiting asynchronous method.

2017-09-05 13:52 UTC, sutrkiller commented on TodoApp/TodoApp.Api.Tests/Controllers/DummyControllerTests_Get.cs
> +            Assert.That(response, Is.InstanceOf<OkNegotiatedContentResult<Todo>>());
Maybe `IsSuccessStatusCode` check is enough? :D

2017-09-05 13:52 UTC, sutrkiller commented on TodoApp/TodoApp.Api.Tests/Controllers/DummyControllerTests_Get.cs
> +            Assert.That(response, Is.EqualTo(mockRepo.GetAll()));
I think it would be better to compare each item or calling something like SequenceEquals...

2017-09-05 13:52 UTC, sutrkiller commented on TodoApp/TodoApp.Api.Tests/Repositories/TodoRepository_Tests.cs
> +        public TodoRepository_Tests()
Convert this to SetUp method == method with `[SetUp]` attribute that run before each test. This should fix the issues with the dependent tests.

2017-09-05 13:52 UTC, sutrkiller commented on TodoApp/TodoApp.Api.Tests/Repositories/TodoRepository_Tests.cs
> +                await _repository.AddAsync(null);
`Assert.Throws<>` ??

2017-09-06 07:57 UTC, medvedovic commented on TodoApp/TodoApp.Api/Repositories/TodoRepository.cs
> +            Todos.Remove(todoToRemove);
Fair point

2017-09-29 08:22 UTC, PetrSvirak requested changes
I haven't seen all the code, however, you made quite some changes since we last talked. Let's redo the review.

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api.Tests/TodoApp.Api.Tests.csproj
> +    <Compile Include="Helpers\UriHelperTests.cs" />
This file is not part of the repository, but it is still part of the project → prevents build.

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api/Helpers/UriHelper.cs
> +        public static void Register(UnityContainer container)
Nope. 
First, why should a helper know what DI container app uses?
Second, it is not an implementation's responsibility to decide a lifecycle it will be used in (~ lifetime manager is not responsibility of a class but the class's user)
Third, if you changed DI container, all your classes would be affected.

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api/Helpers/UriHelper.cs
> +            new Uri(new UrlHelper(request).Route("PostTodo", new { id }), UriKind.Relative);
* Name of the method insists route to anything with ID will be returned. In your implementation, you have to specify a route name (`PostTodo`) though. So it will never be a universal method. The implementation's intention is correct, however, the name is misleading.
* _request_ is actually invariant from controller's point of the lifetime since the `UriHelper` is used only is controllers' dependency, invariantness propagates to it and renders the `HttpRequestMessage` a dependency of the `IUriHelper`
* You create `UrlHelper` each and every time the method is called while the `request` (its only dependency) remains (potentially) unchanged.
* You used `Uri`, nice 👍

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api/Repositories/UnityResolver.cs
> +namespace TodoApp.Api.Repositories
`Resolver` is not a `repository`.

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api/App_Start/WebApiConfig.cs
> +
Let's split the response formatting settings and route settings as they have nothing in common (other than being related to WebApi configuration which is pretty much everything in the project). Rename this class (e.g. to `RouteConfig`) and create a new one (e.g. `FormattingConfig`).

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api/Controllers/TodosController.cs
> +    [RoutePrefix("api/v{version:apiVersion}/todos")]
Either use attribute routing or convention-based, not both, please - having both can lead to unexpected routes when no attribute is specified. It is usually better for API not to work than work with bad routes. Also, if you depended on default route in some controller and not other, changing the default route would lead to unwanted inconsistency.

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api/Controllers/TodosController.cs
> +        [Route("", Name = "PostTodo")]
* You can push the attribute up to the `class` level (eventually even merge it with current `RoutePrefix` attribute). 
* Make the name a public constant within the controller or a standalone class, so it can be reused in `UriHelper`

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api/Controllers/TodosController.cs
> +using TodoApp.Api.Helpers;
This is unused `using` - always remove them since they make class files longer and clutter them. Moreover, there is a feature in both VS and R# that allow unused `usings` removal on whole solution level (making it cheap to maintain).

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Api/Controllers/TodosController.cs
> +        public async Task<IEnumerable<Todo>> GetAllTodos()
* Name the methods by verbs used in HTTP, you will not have to decorate them with `Route` attribute.
* Use `Async` suffix for all async methods (this won't break WebApi's verb resolution (above))

2017-09-29 08:22 UTC, PetrSvirak commented on TodoApp/TodoApp.Contracts/Repositories/ITodoRepository.cs
> +        Task<bool> Update(Guid id, Todo todo);
* Use `Async` suffix (by convention ([SO](https://stackoverflow.com/a/24627122/1138663)))
* Do not name repository and design methods by verbs. You can find inspiration in `LINQ` or `EF`. Rename `Get` to `Find` (e.g.), you do not need `id` in `Update` since it is invariant part of `Todo`.

2017-09-29 12:37 UTC, PetrSvirak requested changes
OK, so I redid the review. I encourage you to go through outdated comments after all (the ones above) + I added some new. Mostly remove validation for now and fix some more or less datails. Before you begin your work on the next task, please, let's discuss your service layer :)

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +            if (todo == null)
The repository is still supposed to be dummy. Do not engage in validation just yet (applies to all validations within the controller). BTW: we will build a service for this, so the controller does not contain any business logic - in this very case, we won't need `null` comparison.

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +            return Created(_uriHelper.BuildUri(newTodo.Id, POST_TODO_ROUTE), newTodo);
Introduce local for the `BuildUri` call.

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/src/TodoApp.Contracts/Models/Todo.cs
> +        [MaxLength(255)]
* First, there is a free line missing above the `attributes`.
* Second, `data annotation` should not be part of the contract – it can be different for data and various application interfaces layers - this is one of the reasons there are usually multiple models, each dedicated to a layer, that are mapped from one to another. Another reason not to use annotation is that reference is scattered all over the solution.

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/src/TodoApp.Contracts/Models/Todo.cs
> +        public override bool Equals(object obj)
This is not needed here. None of your application layers use this method, so it should be part of the API. Usually, it is more fitting to create a comparer for each purpose (since equality changes meaning by context). In your case, place the comparer to your tests layer.

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +        #region SetUp
Remove the regions, please. It would be total overkill here, however, it is possible to split tests into multiple files when necessary (creating a common base class with setup), however, try to keep the file short by other means for now.

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +            _mockRepo.GetAll().Returns(new List<Todo>()
It would be better to store fake `Todo`s in an array variable and reuse this variable in both `mock` and `assert`.

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +            var response = _controller.GetAllTodos();
Make the tests asynchronous. It will allow you to specify `act` correct - your actually do not act in your `act`, you act in your `assert` 😛

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +            CollectionAssert.AreEqual(response.Result, _mockRepo.GetAll().Result);
You should assert `status code` in every test – after all, it is one of the main aspects governing `REST` api…

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +        public async Task<IEnumerable<Todo>> GetAllTodos()
Always return `IHttpActionResult` for consistency. 
It will actually help you in tests as well, since you won't have to assume what `WebAPI` returns in its header when converting non-`ActionResult` to an `ActionResult`.

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +            _mockRepo.Get(Guid.Parse("00000000-0000-0000-0000-000000000000")).ReturnsNull();
Parsing an empty `Guid`? Come on :rofl: (→ `Guid.Empty` 😉 )

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +            Assert.That(responseResult, Is.InstanceOf<OkNegotiatedContentResult<Todo>>());
Do not use `InstanceOf`; first, reflection is a bit slower (does not mind too much in the tests); second, you technically don't mind implementation. I can call `StatusCode(HttpStatusCode.NotFound)` instead of `NotFound()` and test should still pass (since test are there to test behavior, not a concrete way of implementation)

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +        public void PostTodo_ReturnsBadRequest()
Feel free to remove validation tests for now. We will sort out validation in next task (let's discuss it first, though)

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +            Assert.That(responseResult, Is.InstanceOf<CreatedNegotiatedContentResult<Todo>>());
Here, you need to assert `locationUrl` as well (as the response and status code as well).

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/src/TodoApp.Contracts/Helpers/IUriHelper.cs
> +        Uri BuildUri(Guid id, string atRoute);
Parameter `atRoute` actually beats the helper's purpose. It is OK for the route name to be `hardcoded` within the helper since this way your API actually says "call this method to get todo's route" and your tests say "now the route to todo's this" – I would generally vouch for a helper containing multiple methods (one for each route) for both readability and mocking purposes.

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +                .Returns(new Uri("http://localhost/api/v1/todos/56d9ed92-91ad-4171-9be9-11356384ce37"));
The mock should:
* use `Guid` it is given as a parameter (to ensure the expected guid is actually passed to the helper)
* contain different route than tested API (to prevent using other means of routing - such as hardcoded string)

2017-09-29 12:37 UTC, PetrSvirak commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +        private HttpRequestMessage ConfigureRequestMessage()
You actually create the `UriHelper`, so you do not need a method like this.

2017-10-06 10:48 UTC, vit-svoboda requested changes
You seem to have fixed some of the things Petr and Tobias pointed out, but not all. Hopefully, my additional comments won't confuse you too much.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +        public async Task<IHttpActionResult> GetTodoAsync(Guid id)
This is no POST route. The other action is a POST route, but why exactly do you need to name them?

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +        public async Task<IHttpActionResult> GetAllTodosAsync()
I'm not entirely sure whether this API will work with the extra words in action names. I think it should be only HTTP verb and optionally the Async suffix. Otherwise, you'd need attributes such as [HttpGet] and [HttpPost].

Apparently, I lied, it works just fine - the method name only needs to start with the HTTP verb.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +        public const string POST_TODO_ROUTE = "PostTodo";
Constants should be the first "group" among the members.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +            return await Task.FromResult(StatusCode(HttpStatusCode.NoContent));
Maybe this action (and the PUT) should also call the repository, even though it's just a mock.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +    [RoutePrefix("api/v{version:apiVersion}/todos")]
The prefix can be included in the route attribute.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/packages.config
> +  <package id="Antlr" version="3.4.1.9004" targetFramework="net46" />
Why do you reference Antlr? :o

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/packages.config
> +  <package id="jQuery.Validation" version="1.11.1" targetFramework="net46" />
This is only useful for MVC serving the front-end. Clean the project up from stuff like this.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/Helpers/UriHelper.cs
> +[assembly: InternalsVisibleTo("TodoApp.Api.Tests")]
Since this attribute affects the whole assembly, you should place it in the AssemblyInfo.cs - otherwise one would have to search all code files in the assembly to create an idea about the assembly configuration. I can imagine one would be pretty pissed off ;)

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Contracts/Models/Todo.cs
> -        [Required]
Now you have an unused using statement 😱

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Contracts/packages.config
> +  <package id="Unity" version="4.0.1" targetFramework="net46" />
Your contract assembly should not require any fancy NuGets.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/TodoApp.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TodoApp.Repository", "src\TodoApp.DL\TodoApp.Repository.csproj", "{91FEA4CB-008C-4F10-AE8E-77B1C29E8635}"
The folder for TodoApp.Repository project should have the same name. You don't want to know what the urban dictionary says DL means.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.DL/TodoApp.Repository.csproj
> +    <None Include="..\packages.config" />
Why are you looking for the packages.config in solution folder and not the current project folder?

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +using System.Web.Http.Results;
Some more unused usings.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +                new Todo() {Id = new Guid("2e2253c5-4bdb-45d8-8cbf-1a24e9b04d1c"), Value = "Make coffee"},
If you're using the default constructor and object initializer, you can omit the parentheses. Looks super sexy that way.

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/tests/TodoApp.Api.Tests/Controllers/TodosControllerTests.cs
> +
What's up with these double empty lines? Do they have some special meaning?

2017-10-06 10:48 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Contracts/Helpers/IUriHelper.cs
> +        Uri BuildUriForPostTodo(Guid id);
That's an odd name. What is the result URL for?

2017-10-06 12:41 UTC, medvedovic commented on TodoApp/src/TodoApp.Api/packages.config
> +  <package id="Antlr" version="3.4.1.9004" targetFramework="net46" />
Random random = new Random(); :rofl:

2017-10-06 13:16 UTC, medvedovic commented on TodoApp/src/TodoApp.Contracts/packages.config
> +  <package id="Unity" version="4.0.1" targetFramework="net46" />
But IUriHelper references class from Unity; etc.

2017-10-06 13:24 UTC, PetrSvirak commented on TodoApp/src/TodoApp.Contracts/packages.config
> +  <package id="Unity" version="4.0.1" targetFramework="net46" />
No, it does not :stuck_out_tongue:

2017-10-09 08:44 UTC, vit-svoboda requested changes
Nicely done. I think you now have quite a nice solution. Just the fact it's not compilable at the moment is a bit lame.

2017-10-09 08:44 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> -        public const string POST_TODO_ROUTE = "PostTodo";
The constant is still used in `UriHelperTests`. You'll need to get rid of that usage.

2017-10-09 08:44 UTC, vit-svoboda commented on TodoApp/src/TodoApp.Api/Controllers/TodosController.cs
> +            var newTodo = await _repository.UpdateAsync(updated);
The result is actually just a bool according to your interface. It fails a test.

2017-10-09 12:53 UTC, medvedovic commented
Welp, I'm a moron and from now on, you can laugh at me.. Hopefully, it's alright now

2017-10-09 13:11 UTC, vit-svoboda approved these changes
I'm all in for a good laugh, but you're not a moron ;) This happens to everybody unless they're very careful.
I'm quite positive Petr would not like you changing the contract (interfaces) every time it doesn't suit you. However, returning the updated object from the update method seems like a much better design than returning some boolean (What does it mean? Was the item updated?). Just be aware that when you'll implement the actual data layer, you won't be able to change the contract back to a boolean if you find it easier to implement.

2017-10-09 19:01 UTC, merged